# -*- coding: utf-8 -*-
"""review_update.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z8oMp7F7ZsehTBoUj4o6OZ-DQBd4i8wD
"""

"""Install dependencies"""
# !pip install -q google-play-scraper snowflake-connector-python pandas tqdm

"""Import libraries"""
from google_play_scraper import reviews, Sort
import pandas as pd
import snowflake.connector
from datetime import datetime, timedelta
from tqdm import tqdm
import time
import os

"""Snowflake connection parameters """
conn_params = {
    "user": "USER1204",
    "password": os.environ["SNOWFLAKE_PASSWORD"],
    "account": "XUZXIIE-EAC06737",
    "warehouse": "COMPUTE_WH",
    "database": "GPT_REVIEWS_DB",
    "schema": "PUBLIC",
    "role": "ACCOUNTADMIN"
}

"""Connect to Snowflake and get latest uploaded timestamp"""
print("Connecting to Snowflake...")

# Commented out IPython magic to ensure Python compatibility.
    """Upload to Snowflake"""
    print("Uploading new reviews to Snowflake...")

    for _, row in df.iterrows():
        row["created_at"] = row["created_at"].strftime("%Y-%m-%d %H:%M:%S") if pd.notnull(row["created_at"]) else None

        cursor.execute("""
            MERGE INTO reviews AS target
            USING (SELECT %s AS review_id, %s AS user_name, %s AS content,
#                           %s AS score, %s AS created_at, %s AS app_version) AS source
            ON target.review_id = source.review_id
            WHEN MATCHED THEN UPDATE SET
                content = source.content,
                score = source.score,
                created_at = source.created_at,
                app_version = source.app_version
            WHEN NOT MATCHED THEN INSERT (
                review_id, user_name, content,
                score, created_at, app_version
            ) VALUES (
                source.review_id, source.user_name, source.content,
                source.score, source.created_at, source.app_version
            )
        """, tuple(row))

    conn.commit()
    cursor.close()
    conn.close()
    print(" Data upload completed.")